# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: people.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='people.proto',
  package='',
  serialized_pb='\n\x0cpeople.proto\"}\n\x06people\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12%\n\x06gender\x18\x03 \x02(\x0e\x32\x0f.people.gentype:\x04Male\"\x1f\n\x07gentype\x12\x08\n\x04Male\x10\x00\x12\n\n\x06\x46\x65male\x10\x01\"\r\n\x03gen\x12\x06\n\x02mm\x10\x00\"\"\n\x07peoples\x12\x17\n\x06people\x18\x01 \x03(\x0b\x32\x07.people')



_PEOPLE_GENTYPE = _descriptor.EnumDescriptor(
  name='gentype',
  full_name='people.gentype',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Male', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Female', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=95,
  serialized_end=126,
)

_PEOPLE_GEN = _descriptor.EnumDescriptor(
  name='gen',
  full_name='people.gen',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='mm', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=128,
  serialized_end=141,
)


_PEOPLE = _descriptor.Descriptor(
  name='people',
  full_name='people',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='people.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='people.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gender', full_name='people.gender', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PEOPLE_GENTYPE,
    _PEOPLE_GEN,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=141,
)


_PEOPLES = _descriptor.Descriptor(
  name='peoples',
  full_name='peoples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='people', full_name='peoples.people', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=143,
  serialized_end=177,
)

_PEOPLE.fields_by_name['gender'].enum_type = _PEOPLE_GENTYPE
_PEOPLE_GENTYPE.containing_type = _PEOPLE;
_PEOPLE_GEN.containing_type = _PEOPLE;
_PEOPLES.fields_by_name['people'].message_type = _PEOPLE
DESCRIPTOR.message_types_by_name['people'] = _PEOPLE
DESCRIPTOR.message_types_by_name['peoples'] = _PEOPLES

class people(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEOPLE

  # @@protoc_insertion_point(class_scope:people)

class peoples(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEOPLES

  # @@protoc_insertion_point(class_scope:peoples)


# @@protoc_insertion_point(module_scope)
